### ISSUE TITLE
Example wrong?

### ISSUE THREAD

**Issue by johnhaley81** [wokalski/vow#10]
In the example it shows using `map` and not `flatMap` which referencing the following code from the example:

```
Login.logIn () |>
  /* Validates the returned value. Since the vow is handled we don't need to catch*/
  Vow.Result.map (
    fun x =>
      if x##isCancelled {
        Vow.Result.fail LoginRequestCancelled
      } else {
        Vow.Result.return ()
      }
  )
```

returns a result of `Vow.Result.t(Vow.Result.t('value, 'error, handled), 'error, handled)`.

Should this be `flatMap` to get `Vow.Result.t('value, 'error', handled)`?

**Comment by wokalski** [comment]
@johnhaley81 indeed. You’re right.
